version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ahmet
      - MYSQL_ROOT_PASSWORD=qazws1
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - common-net
  recipe-app:
    image: 'ahmet-recipe-app:1.0'
    build:
      context: .
    container_name: recipe-app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:mysql://db:3306/ahmet
      - DB_USERNAME=root
      - DB_PASSWORD=qazws1
    networks:
      - common-net
volumes:
  db:
    driver: local
networks:
  common-net: {}
  